version: '3.1'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 6s
      retries: 10
  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8081:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE
      SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "8082:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE
      SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
  calorie-counter:
    container_name: calorie-counter
    build: ./calorie-counter
    ports:
      - "8080:8080"
    depends_on:
      order-service:
        condition: service_started
      product-service:
        condition: service_started
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8080/products
      ORDER_SERVICE_URL: http://order-service:8080/orders
volumes:
  db: